### ISSUE TITLE
No need for Following page for MVP. Change the search Page to a search bar

### ISSUE THREAD

**Issue by LearnedVector** [btn0513/EBoard#10]

**Comment by exelxior** [comment]
Does it mean that we will only have like 3 tabs top now?

**Comment by LearnedVector** [comment]
For top we need Featured Bulletin Classified and Search. on the bottom tabs we should get rid of chat because we won't be using that for now and replace it with a saved tab so people can easily view their saved products.

**Comment by LearnedVector** [comment]
![img_0683](https://cloud.githubusercontent.com/assets/8495552/7033520/2391c50e-dd40-11e4-84e8-ebc4ea67bbb3.jpg)

the search page should closely resemble this
