### ISSUE TITLE
Modal pop of when you click on image in details page

### ISSUE THREAD

**Issue by LearnedVector** [btn0513/EBoard#12]

**Comment by exelxior** [comment]
Should this branch be merged back to the realtimedata branch?

**Comment by LearnedVector** [comment]
fix the the jsonlisting file so it can pull data first

**Comment by exelxior** [comment]
you guys were working on that, I have no idea about the whole jsonlisting issue...

**Comment by exelxior** [comment]
Merged with mike's branch
