### ISSUE TITLE
Details page: Hide bottom tabs

### ISSUE THREAD

**Issue by exelxior** [btn0513/EBoard#6]

**Comment by exelxior** [comment]
Ended up abandoning the home.details state. Using modal that slide from the bottom to the top to show the details. Press the left button to close the modal. In the future, modal views' details will be updated depend on the post that the user presses.

**Comment by exelxior** [comment]
I think we can definitely also choose other animations instead of sliding from the bottom to the top.

**Comment by exelxior** [comment]
http://ionicframework.com/docs/api/service/$ionicModal/
Hmm, based on the document, seems like we shouldn't use modal for viewing details...

**Comment by LearnedVector** [comment]
So you got rid of the bottom tabs by abandoning the detail state and used the modal right?

I'm looking through your code now

**Comment by exelxior** [comment]
Pretty much. However, passing data to a modal is kinda tricky. I also have not figured out how to hide the bottom tabs without using modal.

**Comment by reggieroby** [comment]
dude do what you said you were going to do. i already made a modal for the map on the details page because i was handling the details page.....  i freaking hate duplicating effort. and plz dont go changing pages im working on when you didnt give me any chance to even give my input on weather it was a good thing to do or not.

**Comment by exelxior** [comment]
dude, I don't know what are you talking about. I did what I said I were going to do. Mike took the profile page and I took the details page from the beginning, besides, I also said that I were going to work on that part yesterday. Perhaps I didn't not say it clearly or loudly enough.

**Comment by exelxior** [comment]
I only changed the your reflow branch only yesterday, and I did admit that was my mistake so please stop saying it all over and over again. Why are you saying that I'm changing pages that you're working on now? What pages? And I only knew that you were working on the login page (auth) and fixing the back button issue yesterday.

**Comment by exelxior** [comment]
We have decided to close this issue!
