### ISSUE TITLE
No History stack for the pages!

### ISSUE THREAD

**Issue by LearnedVector** [btn0513/EBoard#8]
if you click into the details page or the any other pages out of the browse page. It will reset back to the featured page.

**Comment by reggieroby** [comment]
thats because they are tabs there is no history stack for tabs.

**Comment by exelxior** [comment]
I see, I guess this is happening due to referencing one view. But I think we can sort this out soon.

**Comment by exelxior** [comment]
I will put this issue together with the detail page issue.
